### ISSUE TITLE
Hypatia doesn't work with Pyganim 0.9.2

### ISSUE THREAD

**Issue by ibara** [hypatia-engine/hypatia#65]
As requested by @lillian-lemmer 

This is the traceback of Hypatia running with Pyganim 0.9.2
````
/home/brian $ hypatia-demo                                                                                                                                               
Traceback (most recent call last):
  File "game.py", line 35, in <module>
    scene = game.Scene.from_tmx_resource('debug')
  File "/usr/local/lib/python2.7/site-packages/hypatia/game.py", line 268, in from_tmx_resource
    tmx = TMX(file_path)
  File "/usr/local/lib/python2.7/site-packages/hypatia/game.py", line 490, in __init__
    self.tilemap = tiles.TileMap(tilesheet_name, layers)
  File "/usr/local/lib/python2.7/site-packages/hypatia/tiles.py", line 85, in __init__
    tilesheet = Tilesheet.from_resources(tilesheet_name)
  File "/usr/local/lib/python2.7/site-packages/hypatia/tiles.py", line 414, in from_resources
    tile_pyganim = pyganim.PygAnimation(frame_buffer)
  File "/usr/local/lib/python2.7/site-packages/pyganim/__init__.py", line 168, in __init__
    assert frame[1] > 0, 'Frame %s duration must be greater than zero.' % (i)
AssertionError: Frame 0 duration must be greater than zero.
````

**Comment by lillian-lemmer** [comment]
This will be resolved when `CHANGES-EVERYTHING` is merged back to develop and back into master. PygAnim will no longer be a dependency. I also have hardcoded `0.9.0` as the PygAnim version in the `requirements/base.txt`. I think this is sufficient for now?

**Comment by lillian-lemmer** [comment]
Pyganim is no longer used.
