### ISSUE TITLE
Doesn't run on OpenBSD

### ISSUE THREAD

**Issue by ibara** [hypatia-engine/hypatia#96]
What I did:
```
$ git clone https://github.com/hypatia-engine/hypatia.git
$ cd hypatia
$ git checkout -b develop origin/develop
$ cd demo
$ python2.7 game.py
```
Then I get this
```
Traceback (most recent call last):
  File "game.py", line 35, in <module>
    scene = game.Scene.from_tmx_resource('debug')
  File "/usr/local/lib/python2.7/site-packages/hypatia/game.py", line 269, in from_tmx_resource
    human_player = cls.create_human_player(tmx.player_start_position)
  File "/usr/local/lib/python2.7/site-packages/hypatia/game.py", line 239, in create_human_player
    hat = animations.Walkabout('hat')
  File "/usr/local/lib/python2.7/site-packages/hypatia/animations.py", line 335, in __init__
    resource = util.Resource('walkabouts', directory)
  File "/usr/local/lib/python2.7/site-packages/hypatia/util.py", line 72, in __init__
    with zipfile.ZipFile(zip_path) as zip_file:
  File "/usr/local/lib/python2.7/zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: 'resources/walkabouts/hat.zip'
```

**Comment by lillian-lemmer** [comment]
I think this problem is more general than OpenBSD. I believe I have seen this error while testing on my Windows machine. I have another computer to test things out, which will help me rule something out.

It shouldn't even be requesting `hat.zip`... if you look at 239 in game.py in the `develop` branch, it's definitely not `hat = animations.Walkabout('hat')`.

**Comment by ibara** [comment]
Closing this. Problem was on my end. I still had the older version of hypatia installed. Removed it and installed this one cleanly and it works fine.
